### ISSUE TITLE
Cuda Error under self.alpha,p.data - q.data

### ISSUE THREAD

**Issue by ilkarman** [lonePatient/lookahead_pytorch#2]
Hi, I have tried wrapping both torch.optim.Adam (and also RAdam) optimiser, however I get an error when I run this on the gpu:

`File "../optimizer.py", line 35, in step
    q.data.add_(self.alpha,p.data - q.data)
RuntimeError: expected device cuda:0 and dtype Float but got device cpu and dtype Float
`

Using

```
base_optimizer = RAdam(model.parameters(), lr = 0.001)
#base_optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
#optimizer = Lookahead(base_optimizer, k=5, alpha=0.5)
```

Do I have to alter the way I load model and data to gpu? Using standard method of .to(device)

**Comment by ilkarman** [comment]
I think I managed to get this to run by changing self.slow_weights to:

```
        self.slow_weights = [[p.clone().detach().cuda(0) for p in group['params']]
                                for group in self.param_groups]
```

Seems the behaviour of .detach() has changed for the latest pytorch?

**Comment by lonePatient** [comment]
@ilkarman  hi, I add `Radam` and `Ralamb` in `optimizer.py `, I can run on cpu and gpu, if you use cpu ,may be set device `device = torch.device("cpu")` and use gpu:0 `device = torch.device("cuda:0")`

**Comment by ilkarman** [comment]
@lonePatient Sorry it was my stupid fault for casting model to gpu after defining optimiser by accident: https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer/issues/1#issuecomment-524644719

Doing it with proper order I don't need to ast slow_weight params to cuda(0)
